"""Add espn_slot_position to weekly_player_stats

Revision ID: 08add6ea88d6
Revises: 984f22746aca
Create Date: 2026-02-28 11:10:17.862521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08add6ea88d6'
down_revision: Union[str, Sequence[str], None] = '984f22746aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_player_stats', sa.Column('espn_slot_position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_player_stats', 'espn_slot_position')
    # ### end Alembic commands ###
