"""add_scoring_settings_to_leagues

Revision ID: 32173dd2ad32
Revises: f5a3b7c8d1e2
Create Date: 2026-02-26 10:19:32.202269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32173dd2ad32'
down_revision: Union[str, Sequence[str], None] = 'f5a3b7c8d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('scoring_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'scoring_settings')
    # ### end Alembic commands ###
