"""add player_news table

Revision ID: 611db92338ad
Revises: e7b2d9f4a1c3
Create Date: 2026-08-14 22:14:28.332270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611db92338ad'
down_revision: Union[str, Sequence[str], None] = 'e7b2d9f4a1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('espn_headline_id', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'espn_headline_id', name='uq_player_news_headline')
    )
    op.create_index(op.f('ix_player_news_player_id'), 'player_news', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_news_player_id'), table_name='player_news')
    op.drop_table('player_news')
    # ### end Alembic commands ###
