"""add player projections

Revision ID: e7b2d9f4a1c3
Revises: d4a1c6e9b2f7
Create Date: 2026-08-08 18:22:55.578625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b2d9f4a1c3'
down_revision: Union[str, Sequence[str], None] = 'd4a1c6e9b2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_projections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=False),
    sa.Column('floor', sa.Float(), nullable=True),
    sa.Column('ceiling', sa.Float(), nullable=True),
    sa.Column('std_dev', sa.Float(), nullable=True),
    sa.Column('expected_games', sa.Float(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'year', 'week', 'source', name='uq_player_projection')
    )
    op.create_index(op.f('ix_player_projections_player_id'), 'player_projections', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_projections_year'), 'player_projections', ['year'], unique=False)
    # Partial unique index for season rows (week=NULL)
    op.execute('CREATE UNIQUE INDEX uq_player_projection_season ON player_projections (player_id, year, source) WHERE week IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_player_projection_season', table_name='player_projections')
    op.drop_index(op.f('ix_player_projections_year'), table_name='player_projections')
    op.drop_index(op.f('ix_player_projections_player_id'), table_name='player_projections')
    op.drop_table('player_projections')
    # ### end Alembic commands ###
