"""Add stats tables player_season_stats nfl_team_stats player_game_logs

Revision ID: ea608024ec07
Revises: 83d90ca79705
Create Date: 2026-02-16 21:07:34.012021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea608024ec07'
down_revision: Union[str, Sequence[str], None] = '83d90ca79705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_team_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nfl_team', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('total_yards', sa.Integer(), nullable=True),
    sa.Column('pass_yards', sa.Integer(), nullable=True),
    sa.Column('rush_yards', sa.Integer(), nullable=True),
    sa.Column('points_scored', sa.Integer(), nullable=True),
    sa.Column('points_allowed', sa.Integer(), nullable=True),
    sa.Column('pass_yards_allowed', sa.Integer(), nullable=True),
    sa.Column('rush_yards_allowed', sa.Integer(), nullable=True),
    sa.Column('def_rank_vs_qb', sa.Integer(), nullable=True),
    sa.Column('def_rank_vs_rb', sa.Integer(), nullable=True),
    sa.Column('def_rank_vs_wr', sa.Integer(), nullable=True),
    sa.Column('def_rank_vs_te', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfl_team', 'year', 'week', name='uq_nfl_team_year_week')
    )
    op.create_index(op.f('ix_nfl_team_stats_nfl_team'), 'nfl_team_stats', ['nfl_team'], unique=False)
    op.create_table('player_game_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('pass_att', sa.Integer(), nullable=True),
    sa.Column('pass_cmp', sa.Integer(), nullable=True),
    sa.Column('pass_yd', sa.Integer(), nullable=True),
    sa.Column('pass_td', sa.Integer(), nullable=True),
    sa.Column('pass_int', sa.Integer(), nullable=True),
    sa.Column('rush_att', sa.Integer(), nullable=True),
    sa.Column('rush_yd', sa.Integer(), nullable=True),
    sa.Column('rush_td', sa.Integer(), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('rec', sa.Integer(), nullable=True),
    sa.Column('rec_yd', sa.Integer(), nullable=True),
    sa.Column('rec_td', sa.Integer(), nullable=True),
    sa.Column('fumbles', sa.Integer(), nullable=True),
    sa.Column('fumbles_lost', sa.Integer(), nullable=True),
    sa.Column('two_pt_conversions', sa.Integer(), nullable=True),
    sa.Column('fantasy_points', sa.Float(), nullable=True),
    sa.Column('is_active_game', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'year', 'week', name='uq_player_game_log')
    )
    op.create_index(op.f('ix_player_game_logs_player_id'), 'player_game_logs', ['player_id'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('pass_att', sa.Integer(), nullable=True),
    sa.Column('pass_cmp', sa.Integer(), nullable=True),
    sa.Column('pass_yd', sa.Integer(), nullable=True),
    sa.Column('pass_td', sa.Integer(), nullable=True),
    sa.Column('pass_int', sa.Integer(), nullable=True),
    sa.Column('pass_rating', sa.Float(), nullable=True),
    sa.Column('rush_att', sa.Integer(), nullable=True),
    sa.Column('rush_yd', sa.Integer(), nullable=True),
    sa.Column('rush_td', sa.Integer(), nullable=True),
    sa.Column('rush_fumbles', sa.Integer(), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('rec', sa.Integer(), nullable=True),
    sa.Column('rec_yd', sa.Integer(), nullable=True),
    sa.Column('rec_td', sa.Integer(), nullable=True),
    sa.Column('fantasy_points_total', sa.Float(), nullable=True),
    sa.Column('fantasy_points_avg', sa.Float(), nullable=True),
    sa.Column('fantasy_points_per_touch', sa.Float(), nullable=True),
    sa.Column('snap_count', sa.Integer(), nullable=True),
    sa.Column('snap_pct', sa.Float(), nullable=True),
    sa.Column('air_yards', sa.Float(), nullable=True),
    sa.Column('yac', sa.Float(), nullable=True),
    sa.Column('wopr', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'year', name='uq_player_season')
    )
    op.create_index(op.f('ix_player_season_stats_player_id'), 'player_season_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_season_stats_player_id'), table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_index(op.f('ix_player_game_logs_player_id'), table_name='player_game_logs')
    op.drop_table('player_game_logs')
    op.drop_index(op.f('ix_nfl_team_stats_nfl_team'), table_name='nfl_team_stats')
    op.drop_table('nfl_team_stats')
    # ### end Alembic commands ###
