"""add season league tables

Revision ID: f7a2b8c3d9e1
Revises: 611db92338ad
Create Date: 2026-08-24 19:32:30.222006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a2b8c3d9e1'
down_revision: Union[str, Sequence[str], None] = '611db92338ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_runs_league_id'), 'manager_runs', ['league_id'], unique=False)
    op.create_index(op.f('ix_manager_runs_team_id'), 'manager_runs', ['team_id'], unique=False)
    op.create_table('matchups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('bracket_slot', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_points', sa.Float(), nullable=True),
    sa.Column('away_points', sa.Float(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('is_playoff', sa.Boolean(), nullable=True),
    sa.Column('round_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'year', 'week', 'bracket_slot', name='uq_matchup_slot')
    )
    op.create_index(op.f('ix_matchups_league_id'), 'matchups', ['league_id'], unique=False)
    op.create_index(op.f('ix_matchups_week'), 'matchups', ['week'], unique=False)
    op.create_table('lineup_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('set_by', sa.String(), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=True),
    sa.Column('actual_points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'year', 'week', 'player_id', name='uq_lineup_slot_player')
    )
    op.create_index('ix_lineup_slot_team_week', 'lineup_slots', ['team_id', 'year', 'week'], unique=False)
    op.create_index(op.f('ix_lineup_slots_player_id'), 'lineup_slots', ['player_id'], unique=False)
    op.create_table('roster_spots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('acquired_via', sa.String(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('dropped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roster_spot_team', 'roster_spots', ['team_id'], unique=False)
    op.create_index(op.f('ix_roster_spots_league_id'), 'roster_spots', ['league_id'], unique=False)
    op.create_index(op.f('ix_roster_spots_player_id'), 'roster_spots', ['player_id'], unique=False)
    op.create_index('uq_roster_spot_active', 'roster_spots', ['league_id', 'player_id'], unique=True, sqlite_where=sa.text('dropped_at IS NULL'))
    op.add_column('leagues', sa.Column('kind', sa.String(), nullable=False, server_default='espn'))
    op.add_column('leagues', sa.Column('status', sa.String(), nullable=True))
    op.add_column('leagues', sa.Column('current_week', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('regular_season_weeks', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('playoff_teams', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('playoff_start_week', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('draft_snapshot', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('manager_type', sa.String(), nullable=False, server_default='human'))
    op.add_column('teams', sa.Column('ai_strategy', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('ai_profile', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('draft_slot', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('owner_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'owner_user_id')
    op.drop_column('teams', 'draft_slot')
    op.drop_column('teams', 'ai_profile')
    op.drop_column('teams', 'ai_strategy')
    op.drop_column('teams', 'manager_type')
    op.drop_column('leagues', 'draft_snapshot')
    op.drop_column('leagues', 'playoff_start_week')
    op.drop_column('leagues', 'playoff_teams')
    op.drop_column('leagues', 'regular_season_weeks')
    op.drop_column('leagues', 'current_week')
    op.drop_column('leagues', 'status')
    op.drop_column('leagues', 'kind')
    op.drop_index('uq_roster_spot_active', table_name='roster_spots', sqlite_where=sa.text('dropped_at IS NULL'))
    op.drop_index(op.f('ix_roster_spots_player_id'), table_name='roster_spots')
    op.drop_index(op.f('ix_roster_spots_league_id'), table_name='roster_spots')
    op.drop_index('ix_roster_spot_team', table_name='roster_spots')
    op.drop_table('roster_spots')
    op.drop_index(op.f('ix_lineup_slots_player_id'), table_name='lineup_slots')
    op.drop_index('ix_lineup_slot_team_week', table_name='lineup_slots')
    op.drop_table('lineup_slots')
    op.drop_index(op.f('ix_matchups_week'), table_name='matchups')
    op.drop_index(op.f('ix_matchups_league_id'), table_name='matchups')
    op.drop_table('matchups')
    op.drop_index(op.f('ix_manager_runs_team_id'), table_name='manager_runs')
    op.drop_index(op.f('ix_manager_runs_league_id'), table_name='manager_runs')
    op.drop_table('manager_runs')
    # ### end Alembic commands ###
